REALPAGESVC_USERNAME="pynwheel_service"
REALPAGESVC_PASSWORD="FaFGpnB4YNWrHQqi7CBPmH4fITg1Sm"
REALPAGESVC_LICENSE_KEY="a915d9fa-fcb7-4300-97bb-cf3170c946af"
REALPAGE_URL="https://gateway.rpx.realpage.com/RPXGateway/partner/Pynwheel/Pynwheel.svc"
REALPAGE_FLOORPLAN_ACTION ='http://tempuri.org/IRPXService/getfloorplanlist'
REALPAGE_UNIT_ACTION = 'http://tempuri.org/IRPXService/getunitsbyproperty'
REALPAGE_INSERT_PROSPECT = 'http://tempuri.org/IRPXService/insertprospect'
REALPAGE_UPDATE_PROSPECT = 'http://tempuri.org/IRPXService/updateprospect'
REALPAGE_LEASING_AGENT_ACTION = 'http://tempuri.org/IRPXService/getleasingagentsbyproperty'
REALPAGE_ACTIVITY_TYPES_ACTION = 'http://tempuri.org/IRPXService/getactivitytypes'
REALPAGE_MARKETING_SOURCES_ACTION = 'http://tempuri.org/IRPXService/getmarketingsourcesbyproperty'
REALPAGE_INSERT_ACTIVITY_ACTION = 'http://tempuri.org/IRPXService/insertactivity'
REALPAGE_INSERT_UNIT_SHOWN_ACTION = 'http://tempuri.org/IRPXService/insertunitshown'
REALPAGE_INSERT_FOLLOW_UP_ACTION = 'http://tempuri.org/IRPXService/insertfollowup'
REALPAGE_MATRIX_ACTION = 'http://tempuri.org/IRPXService/getrentmatrix'
REALPAGE_PRICE_ACTION = 'http://tempuri.org/IRPXService/getunitlist'
REALPAGE_BUILDING_ACTION = 'http://tempuri.org/IRPXService/getpicklist'
YARDI_LICENSE_KEY= ENV["YARDI_LICENSE_KEY"]