REALPAGESVC_USERNAME="pynwheel_service"
REALPAGESVC_PASSWORD="FaFGpnB4YNWrHQqi7CBPmH4fITg1Sm"
REALPAGESVC_LICENSE_KEY="a915d9fa-fcb7-4300-97bb-cf3170c946af"
REALPAGE_URL="https://gateway.rpx.realpage.com/RPXGateway/partner/Pynwheel/Pynwheel.svc"
REALPAGE_FLOORPLAN_ACTION ='http://tempuri.org/IRPXService/getfloorplanlist'
REALPAGE_UNIT_ACTION = 'http://tempuri.org/IRPXService/getunitsbyproperty'
REALPAGE_PRICE_ACTION = 'http://tempuri.org/IRPXService/getunitlist'
REALPAGE_BUILDING_ACTION = 'http://tempuri.org/IRPXService/getpicklist'
YARDI_LICENSE_KEY="MIIBEAYJKwYBBAGCN1gDoIIBATCB/gYKKwYBBAGCN1gDAaCB7zCB7AIDAgABAgJo
AQICAIAEAAQQnfAySgqwPMdhHb1iJd95EgSByDKj+CmyfBfUL7Qhit2NcOp+3in1
KSEHomH7eFp/el4OgiuJpY/oMdhtAuPF1aY+MQdv4J8Q2Mf3plIjRCmfT3A1lHCs
oSs6PDY2Ee6JUtDu8JZsF79OSsJqo5aHh5iVacBPxEFTv9Il4QPB8BLWE0PjRjZE
cgNVisG7LcOH8pbd8zDLyyTnlsHhpBSFH3r47s2HNpIY3F1M9QwRqhWiQOC/Bsvr
ODNi09KobeykeYuHsR2EgZH79PgzhT29IgszCykEgBy4QqbZ"