# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915690032a6f094d583fdd8ff37905bea7c69ff9bc356bdf5affcd48c19ae5cfdc55583db423f19aa4ef777b6e1649e63e571659bf57df0aa2788396ba701711

test:
  secret_key_base: c41950c28b20a9505bab67f01c89520fedb4c378d83636f6fb293f01563be3cb7ff9d162b99cb45c8788be300a4293326d3d3e255e4452d40a895bb507f6c74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>  
