:concurrency: 5
:queues:
  - restarts
  - message
  - latch_lock
  - delete_data
  - import_data
  - real_page
  - yardi_rent_cafe
  - entrata
  - yardi
  - resman
  - xml
  - zaremba
  - marketing_sources
  - timezone
