import { Icon } from '~/components/Icon';
import { Button } from '~/components/ui';
import type { Unit } from '~/models';
import type { TourStopView } from '~/store/selectors';
import { unitLabel, unitMeta } from '~/store/selectors';
import { LightShell } from './shared';

export const TourCompleteScreen = ({ onSummary }: { onSummary: () => void }) => (
  <LightShell>
    <div className="pw-complete">
      <div className="pw-complete__badge">
        <Icon name="check" size={34} color="var(--pw-primary)" strokeWidth={2.5} />
      </div>
      <div className="pw-complete__title">Tour Complete!</div>
      <div className="pw-complete__sub">You visited all stops.</div>
      <Button style={{ marginTop: 10 }} onClick={onSummary}>
        View Tour Summary
      </Button>
    </div>
  </LightShell>
);

interface SummaryProps {
  propertyName: string;
  visited: TourStopView[];
  notes: Record<string, string>;
  minutes: number;
  unlocked: number;
  bestMatch: Unit | null;
  bestMatchPercent: number;
  bestMatchReasons: string[];
  onApplyBest: () => void;
  onApply: () => void;
  onAi: () => void;
  onShare: () => void;
  onHome: () => void;
  /** ` *` on demo data, so derived text is marked; empty on real data. */
  mark?: string;
}

const recapOf = (propertyName: string, visited: TourStopView[], minutes: number, notes: Record<string, string>, best: Unit | null, mark: string): string => {
  const names = visited.map((v) => v.name);
  let recap = `You explored ${visited.length} stops at ${propertyName} in about ${minutes} minutes`;
  recap += names.length ? `, including ${names.slice(0, 3).join(', ')}${names.length > 3 ? ', and more' : ''}.` : '.';
  const noted = visited.find((v) => notes[v.node]?.trim());
  if (noted) recap += ` You saved a note on ${noted.name}, which suggests it stood out to you.`;
  if (best) recap += ` Based on your route, a ${unitLabel(best).toLowerCase()} home like ${best.name} is your strongest fit${best.available ? ' — it is available now' : ''}.`;
  return `${recap}${mark}`;
};

export const TourSummaryScreen = ({ propertyName, visited, notes, minutes, unlocked, bestMatch, bestMatchPercent, bestMatchReasons, onApplyBest, onApply, onAi, onShare, onHome, mark = '' }: SummaryProps) => (
  <LightShell>
    <div className="pw-summary">
      <div>
        <div className="pw-summary__title">Tour Summary</div>
        <div className="pw-summary__sub">{propertyName} · Completed Today</div>
      </div>
      <div className="pw-summary__stats">
        <div>
          <b>{visited.length}</b>
          <span>Stops</span>
        </div>
        <div>
          <b>{minutes}</b>
          <span>Minutes</span>
        </div>
        <div>
          <b className="pw-summary__primary">{unlocked}</b>
          <span>Unlocked</span>
        </div>
      </div>
      <div className="pw-summary__recap">
        <div className="pw-summary__recaphead">
          <Icon name="sparkle" size={18} color="var(--pw-label-yellow)" />
          <span>AI Tour Recap</span>
        </div>
        <div className="pw-summary__recaptext">{recapOf(propertyName, visited, minutes, notes, bestMatch, mark)}</div>
        <div className="pw-summary__recapfoot">{mark ? 'Generated by Pynwheel AI' : 'Summary of your route'}</div>
      </div>
      {bestMatch ? (
        <div className="pw-summary__best">
          <div className="pw-summary__besthead">
            <span>
              <Icon name="sparkle" size={16} color="var(--pw-primary)" />
              Your Best Match
            </span>
            {bestMatchPercent > 0 ? <b>{bestMatchPercent}% Fit{mark}</b> : null}
          </div>
          <div className="pw-summary__bestbody">
            <div>
              <div className="pw-summary__bestname">{bestMatch.name}</div>
              <div className="pw-summary__bestmeta">{unitMeta(bestMatch, mark)}{bestMatch.available ? ' · Available Now' : ''}</div>
            </div>
            <div className="pw-summary__reasons">
              {bestMatchReasons.map((r) => (
                <span key={r}>{r}</span>
              ))}
            </div>
            <Button height={46} style={{ fontSize: 14 }} onClick={onApplyBest}>
              Apply For {bestMatch.name}
            </Button>
          </div>
        </div>
      ) : null}
      <div className="pw-summary__visited">
        <div className="pw-summary__visitedtitle">Stops You Visited</div>
        {visited.map((v) => (
          <div key={v.node} className="pw-summary__stop">
            <div className="pw-summary__stophead">
              <div className="pw-summary__stopname">{v.name}</div>
              <div className="pw-summary__stopfloor">{v.kind === 'unit' ? v.floorLabel : v.floor}</div>
            </div>
            {notes[v.node]?.trim() ? (
              <div className="pw-summary__note">
                <Icon name="pencil" size={13} color="var(--pw-warn-soft-text)" style={{ flexShrink: 0, marginTop: 2 }} />
                <span>{notes[v.node]}</span>
              </div>
            ) : null}
          </div>
        ))}
      </div>
      <button type="button" className="pw-summary__ai" onClick={onAi}>
        <span className="pw-summary__aiicon">
          <Icon name="sparkle" size={16} color="var(--pw-label-yellow)" />
        </span>
        <span className="pw-summary__aitext">
          <span>Ask The AI Concierge</span>
          <span>Pricing, pet policy, lease terms &amp; more</span>
        </span>
        <Icon name="chevronRight" size={18} color="var(--pw-text-subtle)" />
      </button>
      <div className="pw-summary__actions">
        <Button onClick={onApply}>Apply For A Unit</Button>
        <Button variant="secondary" style={{ fontSize: 15 }} onClick={onShare}>
          Email Me This Summary
        </Button>
        <Button variant="ghost" height={44} onClick={onHome}>
          Back To Home
        </Button>
      </div>
    </div>
  </LightShell>
);
